; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:d1]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
monitor_filters = esp8266_exception_decoder
board_build.filesystem = littlefs


extra_scripts = pre:buildscript_versioning.py
                compressed_ota.py
;uMQTTBroker: Use the latest 2.x core and the setting "lwip Variant: 1.4 High Bandwidth" in the "Tools" menu
; build_flags = -D PIO_FRAMEWORK_ARDUINO_LWIP_HIGHER_BANDWIDTH
lib_deps =
	https://github.com/tzapu/WiFiManager.git
	https://github.com/martin-ger/uMQTTBroker.git
    https://github.com/jwrw/ESP_EEPROM.git